### ISSUE TITLE
Change Pymol Interaction Representation Method

### ISSUE THREAD

**Issue by RMCrean** [kamerlinlab/KIF#4]
Current method to shows contacts between residues involves using a helper script called "draw_links.py" and was available from: "http://pldserver1.biochem.queensu.ca/~rlc/work/pymol/"

This script is no longer available, so a new way is needed, preferably that doesn't require a helper script. 

Should be possible using a distance command (https://pymolwiki.org/index.php/Distance) and then modifying each distance object to reproduce same behavior as before.

**Comment by peterkasson** [comment]
Agreed, drawing by distance is pretty easy.  Getting the "matching" representation of that distance link might take a bit of tweaking.  If it's helpful, I have a script originally designed for MI matrices that goes through and draws them as distances.  But I'm not sure that adds much to what you've figured out already.

https://github.com/kassonlab/analysis-code/blob/master/visualize_mat_as_dist.py

**Comment by RMCrean** [comment]
Thanks, yes it was as you said, I just had to play around with dash settings from the each distance command to get them to match the original representation. I have a version that is working nicely now that I will merge in just a moment.  
![draw_links_fix](https://github.com/kamerlinlab/KIF/assets/49672044/b5ebceea-e7a2-4094-9220-bdc04b48a8ae)
